apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.appName }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.api.appName }}-deployment
  template:
    metadata:
      labels:
        app: control-api
    spec:
      containers:
      - name: api-container
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP