{{- range $role := .Values.roles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ printf "%s-%s" $.Values.global.appName $role.namespace }}
  name: {{ $role.roleName }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
rules:
  - resources: {{ $role.resources | toYaml | nindent 4 }}
    apiGroups: {{ $role.apiGroups | toYaml | nindent 4 }}
    verbs: {{- include "role.parser" $role | }}
---
{{- end -}}
