{{- range $acc := .Values.serviceAccounts }}
{{- range $accRole := $acc.giveRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $acc.name }}-{{ $accRole }}-binding
  namespace: {{ printf "%s-%s" $.Values.global.appName $acc.namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $accRole }}
subjects:
- kind: ServiceAccount
  name: {{ $acc.name }}
  namespace: {{ printf "%s-%s" $.Values.global.appName $acc.namespace }}
---
{{ end }}
{{ end }}
