{{- range $acc := .Values.serviceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $acc.name }}
  namespace: {{ printf "%s-%s" $.Values.global.appName $acc.namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
---
{{- end -}}