services:
  local-registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5000:5000"
  api:
    build:
      context: ../../../ 
      dockerfile: api/Dockerfile
    container_name: api
    ports:
      - "6000:6000"
