version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_DB: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak_data
    ports:
      - 8080:8080
    command:
       start-dev
    depends_on:
      - db
  db:
    image: postgres
    container_name: keycloak_db
    ports:
      - 5050:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      # - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  # oauth-proxy:
  #   image: quay.io/oauth2-proxy/oauth2-proxy:latest
  #   container_name: oauth-proxy
  #   ports: 
  #     - 5000:5000
  #   volumes:
  #     - ./oauth2-proxy.cfg:/etc/oauth2-proxy.cfg
  #   command:
  #     - "--config"
  #     - "/etc/oauth2-proxy.cfg"
  # web:
  #   image: nginx
  #   ports: 
  #   - 80:80