global:
  domainName: kickplate.com
  appName: kickplate
  env: dev
  commonLabels:
    app: kickplate

bases:
  should_deploy: false

namespaces:
  should_deploy: true
  names:
    - kickplate-api
    - kickplate-dashboard
    - kickplate-registry
    - kickplate-keycloak

networking:
  should_deploy: false

registry:
  should_deploy: false
  subdomain: registry
  namespace: kickplate-registry
  appName: registry
  replicas: 1
  imageName: registry
  imageID: 2
  port: 5000

api:
  should_deploy: false
  subdomain: api
  namespace: kickplate-api
  appName: api
  replicas: 1
  imageName: nginx
  imageID: latest
  port: 5000
  serviceAccountName: sa-api

dashboard:
  should_deploy: false
  subdomain: dashboard
  namespace: kickplate-dashboard
  appName: dashboard
  replicas: 1
  imageName: nginx
  imageID: latest
  port: 4000
  serviceAccountName: sa-dashboard

keycloak:
  should_deploy: false
  namespace: kickplate-keycloak
  appName: keycloak

  keycloak:
    port: 8080
    replicas: 1
    imageName: quay.io/keycloak/keycloak
    imageID: latest

  keycloakDB:
    port: 5432
    replicas: 1
    dbName: keycloak_data
    username: kc
    imageName: postgres
    imageID: latest

OAuthProxy:
  should_deploy: true
  namespace: kickplate-keycloak
  appName: auth-proxy
  imageName: quay.io/oauth2-proxy/oauth2-proxy
  imageID: latest
  replicas: 1
  port: 5000

service-account:
  should_deploy: false
  serviceAccounts:
    - name: sa-api
      giveRoles: ["ExecutionGraphReader"]
      namespace: kickplate-api
      createSecret: true
      labels:
        service: api

    - name: sa-dashboard
      giveRoles: ["PodReader"]
      namespace: kickplate-dashboard
      createSecret: true
      labels:
        service: api

  roles:
    - roleName: ExecutionGraphReader
      role: reader
      resources: ["ExecutionGraph"]
      apiGroups: ["v1"]

    - roleName: ExecutionGraphContributor
      role: contributor
      resources: ["ExecutionGraph"]
      apiGroups: ["v1"]

    - roleName: ExecutionGraphOwner
      role: owner
      resources: ["ExecutionGraph"]
      apiGroups: ["v1"]

    - roleName: PodReader
      role: reader
      resources: ["Pods", "Jobs"]
      apiGroups: ["v1"]
