---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - graph.kickplate.com
  resources:
  - EDAG
  verbs:
  - get
  - list
- apiGroups:
  - graph.kickplate.com
  resources:
  - EDAGRuns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - graph.kickplate.com
  resources:
  - EDAGRuns/finalizers
  verbs:
  - update
- apiGroups:
  - graph.kickplate.com
  resources:
  - EDAGRuns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - graph.kickplate.com
  resources:
  - executiongraphruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
