apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: kickplate
    path: ../../base/kickplate
    valuesFile: values-local.yaml
    releaseName: kickplate-v0.1
