{{- if .Values.should_deploy -}}
{{- range $role := .Values.roles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  {{- if not (eq $role.namespace nil) }}
  namespace: {{ $role.namespace | quote }}
  {{- end }}
  name: {{ $role.roleName }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    {{- if not (eq $role.labels nil) }}
    {{ $role.labels | toYaml }}
    {{- end }}
rules:
  - resources: {{ $role.resources | toYaml | nindent 4 }}
    apiGroups: {{ $role.apiGroups | toYaml | nindent 4 }}
    verbs: {{- include "role.parser" $role | }}
---
{{- end -}}
{{- end -}}