{{- range $acc := .Values.serviceAccounts }}
{{- range $accRole := $acc.giveRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $acc.name }}-{{ $accRole }}-binding
  {{ if not $acc.namespace }}
  namespace: {{ $acc.namespace | quote }}
  {{ end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $accRole }}
subjects:
- kind: ServiceAccount
  name: {{ $acc.name }}
  {{ if not $acc.namespace }}
  namespace: {{ $acc.namespace | quote }}
  {{ end }}
{{ end }}
{{ end }}