{{- $proxyFullName := printf "%s-%s" .Values.global.appName .Values.OAuthProxy.appName -}}
{{- if .Values.OAuthProxy.should_deploy -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $proxyFullName }}-config
  {{- if not (eq .Values.keycloak.namespace nil) }}
  namespace: {{ .Values.keycloak.namespace | quote }}
  {{- end }}
data:
    OAUTH2_PROXY_COOKIE_SECRET=fLIblJsthbMhgELnmpqrCbWQD9P1vyDfI5SAs8BUG6c=
    OAUTH2_PROXY_CLIENT_ID=
    OAUTH2_PROXY_CLIENT_SECRET=
    OAUTH2_PROXY_PROVIDER=github
    OAUTH2_PROXY_EMAIL_DOMAINS=*
    OAUTH2_PROXY_GITHUB_USER="github_username"
    OAUTH2_PROXY_REDIRECT_URL=https://auth.yourdomain.com/oauth2/callback
    OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
    OAUTH2_PROXY_COOKIE_DOMAINS=yourdomain.com
    OAUTH2_PROXY_SESSION_STORE_TYPE=cookie
    OAUTH2_PROXY_COOKIE_SAMESITE=lax
    OAUTH2_PROXY_REVERSE_PROXY=true
    OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST=true
    OAUTH2_PROXY_COOKIE_CSRF_EXPIRE=5m
    OAUTH2_PROXY_SCOPE=user:email
    OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=false
    OAUTH2_PROXY_PASS_USER_HEADERS=true
{{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $proxyFullName | quote }}
  {{- if not (eq .Values.OAuthProxy.namespace nil) }}
  namespace: {{ .Values.OAuthProxy.namespace | quote }}
  {{- end }}
spec:
  replicas: {{ .Values.OAuthProxy.replicas }}
  selector:
    matchLabels:
      app: {{ $proxyFullName }}
  template: 
    metadata:
      labels:
        {{ include "common.labels" $ }}
        app: {{ $proxyFullName }}
    spec:
      containers:
      - name: {{ $proxyFullName }}
        image: {{ .Values.OAuthProxy.imageName }}:{{ .Values.OAuthProxy.imageID | default "latest"}}
        ports:
        - containerPort: {{ .Values.OAuthProxy.port }}
{{- end }}