apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  namespace: kickplate-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template: 
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: nginx:latest
        ports:
        - containerPort: 80