apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
# volumes:
#   - name: nginx-router-config
#     configMap:
#       name: nginx-router-config
#       items:
#         - key: nginx.conf
#           path: nginx.conf

apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-postgres-init
data:
  postgres.conf: |
    provider="keycloak"
    provider_display_name="Keycloak"
    login_url="http://keycloak:8080/realms/kickplate/protocol/openid-connect/auth"
    redeem_url="http://keycloak:8080/realms/kickplate/protocol/openid-connect/token"
    validate_url="http://keycloak:8080/realms/kickplate/protocol/openid-connect/userinfo"
    profile_url="http://keycloak:8080/realms/kickplate/protocol/openid-connect/userinfo"
    ssl_insecure_skip_verify=true
    # Client config
    client_id="oauth-proxy"
    client_secret="EWztSlSID7JClVBhNq7p9LFHFek7CQcd"
    cookie_secret="ZzBkN000Wm0pQkVkKUhzMk5YPntQRUw_ME1oMTZZTy0="
    cookie_secure="false"
    # Upstream config
    http_address="0.0.0.0:4180"
    upstreams="file:///dev/null"
    email_domains=["*"]
    oidc_issuer_url="http://keycloak:8080/realms/kickplate"
    cookie_domains=["localhost:80"]
    scope="openid"
    whitelist_domains=["localhost:80*"]
