apiVersion: edag.kickplate.com/v1alpha1
kind: EDAG
metadata:
  labels:
    app.kubernetes.io/name: graphmanager
    app.kubernetes.io/managed-by: kustomize
  name: edag-sample
spec:
  steps:
    step1:
      image: ubuntu:latest
      replicas: 3
      argument: ["sleep", "30"]
    step2:
      image: ubuntu:latest
      replicas: 3
      argument: ["sleep", "30"]