name: "Check Changes"
description: "Checks for changes against HEAD in given directory"

inputs:
  working-directory:
    type: string
    description: "Base directory of python project"
    required: true
outputs:
  is_changed:
    value: ${{ steps.changes.outputs.is_changed }}
    description: "Whether changed have occured"
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch origin/main
      shell: bash
      run: git fetch origin main

    - name: Detected changes
      shell: bash
      run: |
        git diff --name-only origin/main -- ${{ inputs.working-directory }}

    - name: Check for changes
      shell: bash
      id: changes
      run: |
        if git diff origin/main HEAD -- "${{ inputs.working-directory }}"; then
          echo "is_changed=false" >> $GITHUB_OUTPUT
        else
          echo "is_changed=true" >> $GITHUB_OUTPUT
        fi