on:
  workflow_call:
    inputs:
      pipenv-cache-key:
        type: string
        description: "Key to pipenv cache"
        required: true
      
      python-project-path:
        type: string
        description: "Path to python project files"
      
      pipenv-name:
        type: string
        description: "Custom pipenv identifier"
      
      python-version:
        type: string
        description: "Python version to use"
        default: "3.10"


jobs:
  linting:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    
    - name: "Restore pipenv cache"
      uses: actions/cache@v3
      with:
        key: ${{ inputs.pipenv-cache-key }}
        path: |
          ~/.local/share/virtualenvs
          ~/.cache/pip
    
    - name: "Set up python-${{ inputs.python-version }}"
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
    
    - name: Load Pipenv
      run: |
        PIPENV_CUSTOM_VENV_NAME=${{ inputs.pipenv-name }} python -m pipenv install
      
    - name: "Black"
      working-directory: ${{ github.workspace }}/${{ inputs.python-project-path }}
      run: |
        pipenv run black
    
    - name: "Isort"
      working-directory: ${{ github.workspace }}/${{ inputs.python-project-path }}
      run: |
        pipenv run isort
    
    - name: "Flake8"
      working-directory: ${{ github.workspace }}/${{ inputs.python-project-path }}
      run: |
        pipenv run linting
    
    