on:
  push:
    branches:
    - build/python_env

jobs:
  api:
    name: "API"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for api changes
        id: changes
        uses: ./.github/actions/check_changes
        with: 
          working-directory: api

      - name: API main
        if: ${{ steps.changes.outputs.is_changed }} == "true"
        uses: ./.github/workflows/api-main.yml
  tf:
    name: "Infrastructure"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for infrastructure changes
        id: changes
        uses: ./.github/actions/check_changes
        with:
          working-directory: infrastructure

      - name: API main
        if: ${{ steps.changes.outputs.is_changed }} == "true"
        uses: ./.github/workflows/tf-main.yml
