on:
  push:
    branches:
    - main

jobs:
  pipenv_cache:
    name: "Setup Pipenv Cache"
    uses: ./.github/workflows/setup_pipenv.yml
    with:
      python-version: "3.10"
      python-project-path: api
  
  linting:
    name: "Linting"
    uses: ./.github/workflows/linting.yml
    needs: [pipenv_cache]
    with:
      pipenv-cache-key: ${{ needs.pipenv_cache.outputs.cache_key  }}
      python-project-path: "api"
  
  tests:
    name: "Testing"
    uses: ./.github/workflows/python_tests.yml
    needs: [pipenv_cache]
    with:
      pipenv-cache-key: ${{ needs.pipenv_cache.outputs.cache_key  }}
      python-project-path: "api"
