on:
  push:
    branches: _ main

jobs:
  pipenv_cache:
    name: "Setup Pipenv Cache"
    uses: ./.github/workflows/setup_pipenv.yml
    with:
      python_version: "3.10"
      working_dir: api

  linting_and_testing:
    name: "Linting & Testing"
    uses: ./.github/workflows/lint_and_test.yml
    needs: [pipenv_cache]
    with:
      pipenv_cache_key: ${{ needs.pipenv_cache.outputs.cache_key  }}
      working_dir: "api"
      python_version: "3.10"
