on:
  push:
    branches:
    - build/python_env

jobs:   
  lint_and_test:
    name: "Linting & Testing"
    uses: ./.github/workflows/lint-and-test.yml
    with:
      python-project-path: "api"
      python-vesion: "3.10"